In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1


## Introduction to tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()`

In [2]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                     [1,  2]])
MATRIX

tensor([[7, 8],
        [1, 2]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX[1]

tensor([1, 2])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                       [12,34,54],
                       [45,656,23]]])

TENSOR

tensor([[[  1,   2,   3],
         [ 12,  34,  54],
         [ 45, 656,  23]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[  1,   2,   3],
        [ 12,  34,  54],
        [ 45, 656,  23]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors fulls of random tensors and then adjust those random numbers to better represent the data.

In [15]:
# Create Random Tensor of size (3,4)

random_tensor = torch.rand(2, 3, 4)

random_tensor

tensor([[[0.9163, 0.6698, 0.5158, 0.2400],
         [0.7227, 0.6583, 0.0265, 0.8436],
         [0.2769, 0.2083, 0.6162, 0.0159]],

        [[0.3812, 0.5003, 0.1315, 0.8249],
         [0.7833, 0.5554, 0.5851, 0.7754],
         [0.4746, 0.8978, 0.7133, 0.3172]]])

In [16]:
random_tensor.ndim

3

In [17]:
random_tensor.shape

torch.Size([2, 3, 4])

In [18]:
# Create random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224))

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [19]:
torch.rand(3,3)

tensor([[0.1698, 0.0391, 0.7604],
        [0.2941, 0.6492, 0.4668],
        [0.3720, 0.3628, 0.7198]])

### Zeros and Ones

In [20]:
# Create a tensor of all zeros

zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
#create a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
# Use torch.arange()

one_to_ten = torch.arange(start=1, end=10, step=1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# Creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

Tensor datatypes is one of the 3 big errors with PyTorch & Deep learning:
- Tensors not right datatypes
- Tensors not right shape
- Tensors not on the right device

In [25]:
# Float 32 Tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None,       #Datatype of tensor
                               device="cuda",    #What device your tensor on
                               requires_grad=False   #Track the gradients?
                              )

float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [26]:
float_32_tensor.dtype      # Even if we set dtype as none, we get float32

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [28]:
(float_16_tensor * float_32_tensor).dtype   # Float gets multiplied to float

torch.float32

In [29]:
int_32_tensor = torch.tensor([3,5,9], dtype=torch.int32, device="cuda")
int_32_tensor

tensor([3, 5, 9], device='cuda:0', dtype=torch.int32)

In [30]:
float_32_tensor * int_32_tensor            # Changed them to float

tensor([ 9., 30., 81.], device='cuda:0')

### Getting information from tensors  (Tensor Attributes)

1. Tensors not right datatypes - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `torch.device`

In [31]:
# Create a tensor

some_tensor = torch.rand([3,4], dtype=torch.float16, device="cuda")
some_tensor

tensor([[0.7476, 0.7246, 0.6284, 0.0895],
        [0.2003, 0.6533, 0.6982, 0.6035],
        [0.3110, 0.7617, 0.1627, 0.8994]], device='cuda:0',
       dtype=torch.float16)

In [32]:
# Find out detail about tensor

print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device : {some_tensor.device}")

tensor([[0.7476, 0.7246, 0.6284, 0.0895],
        [0.2003, 0.6533, 0.6982, 0.6035],
        [0.3110, 0.7617, 0.1627, 0.8994]], device='cuda:0',
       dtype=torch.float16)
Datatype of tensor:torch.float16
Shape of tensor: torch.Size([3, 4])
Device : cuda:0


### Manipulating Tensors (tensor operations)

Tensor operations include: 
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix Multiplication

In [33]:
# Create a tensor and add 10 to it

tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [34]:
# Multiply by 10

tensor * 10

tensor([10, 20, 30])

In [35]:
# Subtract 10
tensor -10 

tensor([-9, -8, -7])

In [36]:
# Try out PyTorch in-built functions

torch.mul(tensor, 10)

tensor([10, 20, 30])

In [37]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networds and deepp learning:

1. Element-wise Multiplication
2. Matrix Multiplication (dot product)

There are two main rules that performing matrix multiplications need to satisfy:
1. The **inner Dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimension**:
* `(2,3) @ (3,2)` -> `(2,2)`

In [38]:
# Element-Wise Multiplication

print(tensor ,'*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [39]:
# Matrix Multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [40]:
tensor

tensor([1, 2, 3])

In [41]:
# Matrix Multiplication by hand

1*1 + 2*2 + 3*3

14

In [42]:
%%time

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
    
value

CPU times: total: 0 ns
Wall time: 1 ms


tensor(14)

In [43]:
%%time

torch.matmul(tensor, tensor)          # Much faster than loop

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning: Shape Errors

In [45]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1, 2], 
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A, tensor_B)    #torch.mm is same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [46]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate theshape of one of our tensors using **transpose** .

A **transpose** switches the axes or dimensions of a given tensor.

In [47]:
tensor_B.T , tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [48]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [49]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original Shape: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New Shape: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions now match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original Shape: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New Shape: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions now match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum etc  (tensor aggregation)

In [50]:
# Create a tensor

x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [51]:
# Finding min

torch.min(x), x.min()

(tensor(1), tensor(1))

In [52]:
# Finding max

torch.max(x), x.max()

(tensor(91), tensor(91))

In [53]:
# Finding mean - note: torch.mean() function requires a tensor of float32 dtype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [54]:
# Finding sum

torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [55]:
torch.argmax(x)

tensor(9)

## Finding the positional min and max

In [56]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [57]:
# Find the position in tensor that hs the minimum value with argmin() -> returns index position of target tensor where meinimum value occurs

x.argmin() , x[0]

(tensor(0), tensor(1))

In [58]:
# Find the position in tensor that has the maximum value with argmax()

x.argmax(), x[9]

(tensor(9), tensor(91))

## Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshapes an input toensor to a defined shape
* View -  Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Remove all `1` dimensions from a tensor
* Unsqueeze -  add a `1` dimension to a target tensor
* Permute -  return a view of the input with dimensios permuted (swapped) in a certain way

In [59]:
# Create a tensor

import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [60]:
# Add an extra dimension

x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [62]:
# Change the  view    (z shares same memory as x)

z =  x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [63]:
# Changing z changes x (becoz a view of a tensor shares same memory)

z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [64]:
# Stack tensors on top of each other

x_stacked = torch.stack([x,x,x,x])
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [65]:
# Stack tensors side by side

x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [66]:
# Squeeze - Removes all single dimensions from a target tensor

print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


In [67]:
# Unsqueeze -  Adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Adds an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New Shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Shape: torch.Size([1, 9])


In [68]:
# torch.permute -  rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))  #[height, width, color_channel]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)   # shifts axis 0->1 , 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}")    #[color_channel, height, width]

# It shares the same memory as original ones

Previous shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [69]:
# Create a tensor

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [70]:
# Let's index on our new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [71]:
# Let's index on middle bracket (dim=1)

x[0][0]

tensor([1, 2, 3])

In [72]:
# Let's index on most inner bracket (last dim)

x[0][1][0]

tensor(4)

In [73]:
# You can use ":" to select "all" of a target dimension

x[:, 0]

tensor([[1, 2, 3]])

In [74]:
# Get all values of 0th and first dimensions but only index 1 of 2nd dimension

x[:, :, 1]

tensor([[2, 5, 8]])

In [75]:
# Get all values of 0th dimension buyt only the 1 index value of 1st and 2nd dim

x[:, 1, 1]

tensor([5])

In [76]:
# Get index 0 of 0th and 1st dim and all values of 2nd dim
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch Tensors and NumPy

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [77]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)       # Default dtype = float64
tensor = torch.from_numpy(array).type(torch.float32) # Changed from float64 to 32
array, tensor 

# warning: when converting from numpy -> pytorch, PyTorch reflects numpy's default datatype of float64 unless specified otherwise

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [78]:
# Change the value of array, what will it do to tensor?

array = array + 1

array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [79]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [80]:
# Change the tensor, what ahppens to the numpy_tensor?

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take random out of random)

In short how a neural network learns: 

`start with random number -> tensor operations -> update rnadom numbers to try and make them better representations of the data -> again -> again....`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed** 

Essentially, what random seed does is "flavour" the randomness. 

In [81]:
# Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6451, 0.4562, 0.1222, 0.0301],
        [0.0043, 0.0052, 0.8652, 0.7221],
        [0.2280, 0.6271, 0.4368, 0.8520]])
tensor([[0.4474, 0.3816, 0.2944, 0.1226],
        [0.0180, 0.1070, 0.3540, 0.9191],
        [0.0327, 0.7736, 0.9276, 0.7979]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [82]:
# Let's make some random but reproducible tensors

# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)         # We need to define everytime.
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs (faster computations)

GPU = faster computation on numbers, thanks to CUDA + Nvidia hardware + PyTorch

In [83]:
# Check for GPU access with PyTorch

torch.cuda.is_available()

True

*It's a good practice to setup device agnostic code everytime to get gpu*

In [84]:
# Setup device agostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [85]:
# Count number of devices

torch.cuda.device_count()

2

### Putting tensors (and models) on the GPU

The reason we want out tensors/model on GPU is becasue using a GPU results in faster computations.

In [86]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [87]:
# Move tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Move tensors back to the CPU

In [88]:
# If tensor is on GPU, can't transform it to numpy

tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [89]:
# to fix the GPU tensor with NumPy issue, we can first set it to the CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

---

# Exercises & Extra-Curriculum

In [90]:
RANDOM_SEED = 1234

device = "cuda" if torch.cuda.is_available() else "cpu"

torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(2,3).to(device)

tensor_B = torch.rand(2,3).to(device)

tensor_A, tensor_B

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [91]:
matmul = torch.mm(tensor_A, tensor_B.T)
matmul

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [92]:
torch.max(matmul)

tensor(0.5617, device='cuda:0')

In [93]:
torch.min(matmul)

tensor(0.3647, device='cuda:0')

In [94]:
torch.argmax(matmul)

tensor(3, device='cuda:0')

In [95]:
torch.argmin(matmul)

tensor(0, device='cuda:0')

In [96]:
torch.manual_seed(7)
new_rand = torch.rand(1, 1, 1, 10)
new_rand, new_rand.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [97]:
torch.manual_seed(7)
torch.squeeze(new_rand).shape

torch.Size([10])